[FEATURE] adding error Messages to login page
rodrigo-cervone/bootcamp pull request #2
Opened 2017-03-15 18:14 UTC by jhcruz

2017-03-15 21:25 UTC, rodrigo-cervone requested changes

2017-03-15 21:25 UTC, rodrigo-cervone commented on src/pages/user-login/user-login.html
> +                 ></ion-input>
Please merge these two lines.

2017-03-15 21:25 UTC, rodrigo-cervone commented on src/pages/user-login/user-login.ts
>            return this.logger.debug("Show bad credentials message");
Just remove the logger here.

2017-03-17 00:06 UTC, jhcruz commented
Resolved Comments ...

2017-03-17 15:43 UTC, rodrigo-cervone approved these changes

2017-03-17 15:44 UTC, merged