Feature profile page
rodrigo-cervone/bootcamp pull request #3
Opened 2017-03-15 18:16 UTC by jhcruz

2017-03-15 21:29 UTC, rodrigo-cervone commented on src/pages/user-edit/user-edit.ts
> +  enviar(Otro: Object){
english pls

2017-03-17 15:46 UTC, rodrigo-cervone commented
@jhcruz Please, review the conflicts in this PR.

2017-03-17 17:11 UTC, jhcruz commented
Conflicts resolved.

2017-03-17 18:36 UTC, rodrigo-cervone commented
Overall looking good. Just some minor comments.

2017-03-17 18:37 UTC, rodrigo-cervone requested changes

2017-03-17 18:37 UTC, rodrigo-cervone commented on src/models/user.model.ts
> +export interface User extends UserEntity{
Why are you extending an interface from a class? Can't you just add the missing properties in the User and use that? It looks, at least, weird.

2017-03-17 18:37 UTC, rodrigo-cervone commented on src/pages/user-details/user-details.ts
> +      //Nothing
Please, just remove the method.

2017-03-17 18:37 UTC, rodrigo-cervone commented on src/pages/user-edit/user-edit.ts
> +  ionViewDidLoad() {
Same here. Just remove the method.

2017-03-17 18:37 UTC, rodrigo-cervone commented on src/pages/user-edit/user-edit.ts
> +  send(){
Please, add a @TODO here with the intended behavior.

2017-03-17 18:37 UTC, rodrigo-cervone commented on src/pages/user-login/user-login.ts
> +  //public sessionService: SessionService;
Remove this line, please.

2017-03-27 17:11 UTC, rodrigo-cervone commented
Looking good. Please resolve the conflicting files and we can merge it. Thanks for the changes.

2017-03-27 17:21 UTC, merged