Mocking services.
rodrigo-cervone/bootcamp pull request #5
Opened 2017-03-17 22:27 UTC by rodrigo-cervone

2017-03-20 15:48 UTC, rodrigo-cervone commented
Implements some mocking data.

2017-03-23 18:23 UTC, jhcruz requested changes

2017-03-23 18:23 UTC, jhcruz commented on src/mock-bootcamp-backend/mock-github-backend.service.ts
> +    private passThrough(connection: MockConnection) {
Documentation

2017-03-27 15:59 UTC, urieljbm commented
All looks fine.

2017-03-27 16:42 UTC, merged