[POC] - Adding multilanguage support
rodrigo-cervone/bootcamp pull request #8
Opened 2017-03-23 15:08 UTC by rodrigo-cervone

Implements a module to translate the UI

2017-03-23 18:23 UTC, jhcruz requested changes

2017-03-23 18:23 UTC, jhcruz commented on src/pages/user-details/user-details.ts
> +  changeLanguage() {
Documentation

2017-03-23 18:23 UTC, jhcruz commented on src/pages/user-details/user-details.ts
> +  onToggleChange() {
documentation

2017-03-23 18:23 UTC, jhcruz commented on src/i18n/i18n.service.ts
> +export const LANG_ES_NAME = 'es';
Is not better use it this const on an array?

2017-03-23 18:23 UTC, jhcruz commented on src/i18n/lang/dict.es.ts
> +export const LANG_ES_TRANS = {
the solution could to apply a complex lines? like "Welcome {name}", where "name" is a variable

2017-03-23 18:23 UTC, jhcruz commented on src/app/app.module.ts
> +import { I18nModule } from '../i18n/i18n.module';
this module is from Angular?
import { TRANSLATIONS, TRANSLATIONS_FORMAT, LOCALE_ID } from '@angular/core';
https://angular.io/docs/ts/latest/cookbook/i18n.html

2017-03-23 18:28 UTC, rodrigo-cervone commented on src/pages/user-details/user-details.ts
> +  changeLanguage() {
sure

2017-03-23 18:28 UTC, rodrigo-cervone commented on src/pages/user-details/user-details.ts
> +  onToggleChange() {
sure *2

2017-03-23 18:28 UTC, rodrigo-cervone commented on src/i18n/i18n.service.ts
> +export const LANG_ES_NAME = 'es';
could be, I'll change it

2017-03-23 18:29 UTC, rodrigo-cervone commented on src/i18n/lang/dict.es.ts
> +export const LANG_ES_TRANS = {
Didn't try that. I'll change it to see what happens.

2017-03-23 18:31 UTC, rodrigo-cervone commented on src/app/app.module.ts
> +import { I18nModule } from '../i18n/i18n.module';
mmm... no... is a custom implementation. I didn't saw that module. Good catch.

2017-03-27 16:00 UTC, urieljbm commented
All looks fine.

2017-03-27 17:05 UTC, merged